host: localhost
port: 3000
multer:
  fileSize: 50000000 # In Byte. 50MB
  files: 1
  storage_path: uploads/
  fieldNames:
    - name: file
    - name: fileCategory
mongodb:
  uri: mongodb+srv://challengeUser:WUMglwNBaydH8Yvu@challenge-xzwqd.mongodb.net/getir-case-study?retryWrites=true
  debug: true
  config:
    autoIndex: true
    useCreateIndex: true
    useNewUrlParser: true
    useUnifiedTopology: true
    poolSize: 10
    promiseLibrary: Bluebird
# log configuration
logFile:
  filename: api
  maxsize: 50m
  dirname:  logs
  prepend: true
  json: false
  utc: true
  extension: log
  zippedArchive: true
  datePattern: YYYY-MM-DD-
  level: debug
swaggerUI:
  username: admin
  password: kpysPsLp2l2FckcBdX0IDD6t